name: example
description: >
  The QR.Flutter example app.
version: 1.0.0+1
author: Yakka, LLC <hello@yakka.agency>
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/logo_yakka.png
